---
name: build-ublue-custom

on:
  schedule:
    - cron: "5 10 * * *"
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"
  workflow_dispatch:

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    env:
      IMAGE_SOURCE: "ghcr.io/ublue-os/silverblue-main"
      IMAGE_VERSION: "41"
      IMAGE_NAME: "${{ github.event.repository.name }}"
      IMAGE_DESCRIPTION: "Fedora Silverblue Custom"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Maximize build space
        uses: ublue-os/remove-unwanted-software@v7

      - name: Pull source image
        uses: Wandalen/wretry.action@v3.7.2
        with:
          attempt_delay: 15000
          attempt_limit: 3
          command: |
            podman pull ${{ env.IMAGE_SOURCE }}:${{ env.IMAGE_VERSION }}

      - name: Set image tag
        id: image_tag
        uses: Wandalen/wretry.action@v3.7.2
        with:
          attempt_delay: 15000
          attempt_limit: 3
          command: |
            set -eu -o pipefail
            upstream_tag=$(skopeo inspect docker://${{ env.IMAGE_SOURCE }}:${{ env.IMAGE_VERSION }} | jq -r '.Labels["org.opencontainers.image.version"]')
            echo "tag=$upstream_tag" >> $GITHUB_OUTPUT

      - name: Set image metadata
        uses: docker/metadata-action@v5
        id: image_metadata
        with:
          images: |
            ${{ env.IMAGE_NAME }}
          labels: |
            io.artifacthub.package.readme-url=https://raw.githubusercontent.com/${{ github.repository }}/HEAD/README.md
            org.opencontainers.image.title=${{ env.IMAGE_NAME }}
            org.opencontainers.image.description=${{ env.IMAGE_DESCRIPTION }}
            org.opencontainers.image.version=${{ steps.image_tag.outputs.tag }}

      - name: Build image
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: |
            ./Containerfile
          image: ${{ env.IMAGE_NAME }}
          build-args: |
            IMAGE_SOURCE=${{ env.IMAGE_SOURCE }}
            IMAGE_VERSION=${{ env.IMAGE_VERSION }}
          tags: ${{ steps.image_tag.outputs.tag }} latest
          labels: ${{ steps.image_metadata.outputs.labels }}
          oci: false

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image
        uses: Wandalen/wretry.action@v3.7.2
        id: push
        env:
          REGISTRY_USER: ${{ github.actor }}
          REGISTRY_PASSWORD: ${{ github.token }}
        with:
          action: redhat-actions/push-to-registry@v2
          attempt_delay: 15000
          attempt_limit: 3
          with: |
            image: ${{ steps.build_image.outputs.image }}
            tags: ${{ steps.build_image.outputs.tags }}
            registry: ghcr.io/${{ github.repository_owner }}
            username: ${{ env.REGISTRY_USER }}
            password: ${{ env.REGISTRY_PASSWORD }}
            extra-args: |
              --disable-content-trust
